namespace rvb.scripts {
    // 角色子状态
    public enum SheepRoleSubState {
        None = 0,
        In = 1,
        Spurt = 2,
        MoveTar = 3,
        MoveBoss = 4,
        AttackAwait = 5,
        AttackAnim = 6,
        Dead = 7,
        DeadMerge = 8,
        KillerStart = 9,
        Killer1 = 10,
        Killer2 = 11,
        Killer3 = 12,
        Killer4 = 13,
        Killer5 = 14,
        Killer6 = 15,
        Killer7 = 16,
        Killer8 = 17,
        Killer9 = 18,
        KillerEnd = 19,
        Boom = 20,
        Invincible = 21,
        Bladestorm = 22,
        Res = 23,
        Palm = 24,
        CallBullets = 25,
        Buff = 26,
        Up = 27,
        Start = 28,
        Charge = 29,
        ChargePlus = 30,
    }
}